// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9shMMTPOMDlhlzjOpRxX4ch7lmGwIvNE',
    appId: '1:251194460438:web:497beea0679fbc96d96837',
    messagingSenderId: '251194460438',
    projectId: 'horarios-fisei',
    authDomain: 'horarios-fisei.firebaseapp.com',
    storageBucket: 'horarios-fisei.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNN-YIsx9cesV3sURTMMQyjH5ITpghbuY',
    appId: '1:251194460438:android:ac624f7eba2d74c4d96837',
    messagingSenderId: '251194460438',
    projectId: 'horarios-fisei',
    storageBucket: 'horarios-fisei.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA26f_BqRpTk057hiNwZxAs5IAwaKWd8sk',
    appId: '1:251194460438:ios:68045091ae38f236d96837',
    messagingSenderId: '251194460438',
    projectId: 'horarios-fisei',
    storageBucket: 'horarios-fisei.appspot.com',
    androidClientId: '251194460438-mk2t1p7ip6o22npl3tlolildd26potep.apps.googleusercontent.com',
    iosBundleId: 'com.example.dashboardFisei',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA26f_BqRpTk057hiNwZxAs5IAwaKWd8sk',
    appId: '1:251194460438:ios:0d72865aef6cb230d96837',
    messagingSenderId: '251194460438',
    projectId: 'horarios-fisei',
    storageBucket: 'horarios-fisei.appspot.com',
    androidClientId: '251194460438-mk2t1p7ip6o22npl3tlolildd26potep.apps.googleusercontent.com',
    iosBundleId: 'com.example.dashboardFisei.RunnerTests',
  );
}
